services:
  postgres:
    image: postgres:17
    container_name: user_postgres
    environment:
      POSTGRES_DB: p_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s
      start_period: 10s

  user-service:
    build:
      context: ./user-service          # 루트
      dockerfile: Dockerfile  # 루트에 있는 Dockerfile 사용
    container_name: user_service
    ports:
      - "9006:9006"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/p_users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin1234
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  pgdata:
