server:
  port: ${API_GATEWAY_PORT}

spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  cloud:
    gateway:
      routes:
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/v1/hub/**
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정

management:
  endpoints:
    web:
      exposure:
        include: refresh