server:
  port: ${ORDER_SERVICE_PORT}

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: true

mq:
  exchange:
    order: order.exchange
    delivery: delivery.exchange
  queue:
    order: order.queue.delivery.create
  routing_key:
    order:

