server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  datasource:
    url: jdbc:postgresql://postgres-db-order:5432/order_db
    username: postgres
    password: 123
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq-server}
    port: 5672
    username: ${RABBIT_USERNAME:your_rabbitmq_user}
    password: ${RABBIT_PASSWORD:your_rabbitmq_password}
  cache:
    type: redis
    redis:
      time-to-live: 3600s
  data:
    redis:
      host: ${REDIS_HOST:redis-server}
      port: 6379

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_DEFAULT_ZONE}
#    register-with-eureka: true
#    fetch-registry: true

mq:
  order:
    queue:
      delivery:
        created: order.queue.delivery.created
        completed: order.queue.delivery.completed
    exchange: order.exchange
    routing_key:
      delivery:
        created: order.delivery.created
        completed: order.delivery.completed
  delivery:
    queue:
      order:
        created: delivery.queue.order.created
      hub:
        route:
          created: delivery.queue.hub.route.created
    exchange: delivery.exchange
    routing_key:
      order:
        created: delivery.order.created
      hub:
        route:
          created: delivery.hub.route.created
  hub:
    queue:
      route:
        request: hub.queue.hub.route.request
    exchange: hub.exchange
    routing_key:
      delivery:
        route:
          request: hub.delivery.route.request